CREATE TABLE IF NOT EXISTS faults (
    id INTEGER PRIMARY KEY AUTO_INCREMENT UNIQUE ,
    title VARCHAR(60) NOT NULL unique,
    description TEXT NOT NULL,
    image_path VARCHAR(250) NOT NULL unique,
    fixed BIT DEFAULT 0,
    building_id INTEGER,
    CONSTRAINT FK_FaultBuilding FOREIGN KEY (building_id) REFERENCES buildings (id) ON DELETE CASCADE
);

INSERT INTO faults(title, description, image_path, building_id)
VALUES
("NIeszczelne okno","W klatce II na 2 pietrze jest problem ze szczelnoscia okna na klatce schodowej. Podczas chlodniejszych dni zimne powietrze przedostaje sie miedzy oknem a futryna przez co w klatce jest schodowej spada temperatura",
 "/1.png",1),
("Problem ze szczelnscoscia okna","W klatce I na 3 pietrze woda przedostaje sie miedzy oknem a sciana. Na zdjeciu widac zawilgocenie, podczas opadow znaczna ilosc wody zbiera sie na parapecie",
 "/2.png",5),
("Awaria domofonu","Na wyswietlaczu domofonu widnieje komunikat error. Drzwi sa ciagle zamkniete wiec jestesmy zmuszni uzywac klucza aby otworzyc drzwi",
 "/3.png",1),
("Popsuty klawisz w domofononie","Po wcisnieciu klawisza 2 domofon wyswietla cyfre 3. Powoduje to brak mozliwosci wpisania poprawnego kodu. Czesc mieszkancow musi uzywac klucza do otwierania drzwi. Przycisk 3 jak i pozostale klawisze dzialaja poprawnie",
 "/4.png",2),
("Stojaca woda w piwnicy","Po opadach deszczu zbiera siw woda na posadzce w piwnicy, W przypadku bardziej wilgotnych dni widac tez zawilgocenie sasiednich scian. Problem zaczal sie po ostatnim remoncie",
 "/5.png",2),
("Urwana klamka","Urwana klamka od drzwi do piwnicy. Prosze o naprawe, ciezko jest dostac sie do piwnicy po rower",
 "/6.png",2),
("Zalany sufit","Na ostanim 4 pietrze widac wilgoc na suficie w klatce schodowej. dzieje sie tak zwykle po nawet niewielkich opadach deszczu. Problem pojawil sie po ostanim remoncie dachu 2 tyg temu",
 "/7.png",2),
("Problem z oswietleniem","Na pierwszym pietrze jedna z lamp na korytarzu swieci slabiej od drugiej. Czasami dochodzi migotanie. Wiec czasami sie włączy a czasmai nie",
 "/8.png",2),
("Porysowana winda","W drugiej klatce po ostatnim weekendzie ktos porysowal winde. Dziala poprawnie ale jak widac na zdjeciu jest lakier jest mocno uszkodzony",
 "/9.png",3),
("Urwana klamka windy","Klamka od windy zostala urwana",
 "/10.png",2),
("Uszkodzona winda","Jak widac na zdjeciu winda zostala powaznie uszkodzona. Nie funkcjonuje prawidlowo i stanowi zagrozenie dla dzieci",
 "/11.png",3),
("Uszkodzone drzwi wejsciowe","Jak na zdjeciu. Drzwi wejsciowe budynku w klatce I zostaly uszkodzone. Szybva trzyma sie na miejscu jednak jest na tyle uszkodozna ze w kazdej chwili moze wypasc i zrobic komus krzywde. Prosze o pilna naprawe ",
 "/12.png",4),
("Urwana klamka okna","Klamka okna na 3 pietrze zostala urwana. Problem z ta klamka byl juz od 2 miesiecy. Zglaszalismy wielokrotnie, po naprawach wielokrotnie \"luzowala\" sie juz po kilku dniach az  wkoncu sie urwala. w chwili obecnej okno sie ciagle otwarte, co powoduje obnizenie tempereatury w klatce jak i pewny zagrozenie dla dzieci",
 "/13.png",4),
("Odpadajaca farba","W klatce schodowej nr 2 na drugim pietrze farba odpada ze sciany (zdjecie)",
 "/14.png",4),
("Zacinajaca sie brama","Problem tyczy sie automatycznej bramy wjzadowej. Dosc czest sie \"zacina\", tzn otwiera sie do polowy, zatrzymuje i ponownie zamyka. Sytuacja jest podobna przy zamykaniu. Moze miec to zwiazaek, choc moze tego nie widac na zdjeciu iz wydaje sie ona skrzywiona, moze po ostaniej gololedzi bylo uderzone w brame autem",
 "/15.png",5),
("Uszkodzona szyba przy balustradzie","Uszkodozna szyba przy balustradzie stanowi zagrozenie dla przechodniow i osob stawiajacych rowery przy scianie do ktorej zamontowana jest obrecz. Prosze o naprawe",
 "/16.png",5);