ALTER TABLE contracts DROP CONSTRAINT FK_ContractFlat;
ALTER TABLE contracts DROP CONSTRAINT FK_ContractUser;
ALTER TABLE contracts DROP CONSTRAINT FK_ContractFee;

ALTER TABLE contracts ADD CONSTRAINT FK_ContractFlat FOREIGN KEY (flat_id) REFERENCES flats (id) ON DELETE CASCADE;
ALTER TABLE contracts ADD CONSTRAINT FK_ContractUser FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE contracts ADD CONSTRAINT FK_ContractFee FOREIGN KEY (fee_id) REFERENCES fees (id) ON DELETE CASCADE;