
INSERT INTO users(username,email,password,role) VALUES
('admin','admin@gmail.com',"$2a$10$PoGvYb0nghiXtYyrd9HG/u5EV9xdcgDTifXii4q9y9gB7QUPtCjkm",'ADMIN'),

('Barbara Wojcik','barbara.wojcik@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Adam Wojcik','adam.wojcik@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Cecylia Wojcik','cecylia.wojcik@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Daniel Wojcik','daniel.wojcik@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Eryk Wojcik','eryk.wojcik@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Albert Wojcik','albert.wojcik@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Pawel Wojcik','pawel.wojcik@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Iza Wojcik','iza.wojcik@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Monika Wojcik','monika.wojcik@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Anna Wojcik','anna.wojcik@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),

('Barbara Kowalski','barbara.kowalski@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Adam Kowalski','adam.kowalski@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Cecylia Kowalski','cecylia.kowalski@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Daniel Kowalski','daniel.kowalski@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Eryk Kowalski','eryk.kowalski@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Albert Kowalski','albert.kowalski@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Pawel Kowalski','pawel.kowalski@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Iza Kowalski','iza.kowalski@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Monika Kowalski','monika.kowalski@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Anna Kowalski','anna.kowalski@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),

('Barbara Nowak','barbara.nowak@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Adam Nowak','adam.nowak@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Cecylia Nowak','cecylia.nowak@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Daniel Nowak','daniel.nowak@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Eryk Nowak','eryk.nowak@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Albert Nowak','albert.nowak@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Pawel Nowak','pawel.nowak@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Iza Nowak','iza.nowak@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Monika Nowak','monika.nowak@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Anna Nowak','anna.nowak@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),

('Barbara Hajto','barbara.hajto@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Adam Hajto','adam.hajto@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Cecylia Hajto','cecylia.hajto@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Daniel Hajto','daniel.hajto@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Eryk Hajto','eryk.hajto@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Albert Hajto','albert.hajto@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Pawel Hajto','pawel.hajto@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Iza Hajto','iza.hajto@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Monika Hajto','monika.hajto@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Anna Hajto','anna.hajto@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),

('Barbara Stoch','barbara.stoch@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Adam Stoch','adam.stoch@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Cecylia Stoch','cecylia.stoch@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Daniel Stoch','daniel.stoch@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Eryk Stoch','eryk.stoch@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Albert Stoch','albert.stoch@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Pawel Stoch','pawel.stoch@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Iza Stoch','iza.stoch@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Monika Stoch','monika.stoch@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Anna Stoch','anna.stoch@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),

('Barbara Blachowicz','barbara.blachowicz@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Adam Blachowicz','adam.blachowicz@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Cecylia Blachowicz','cecylia.blachowicz@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Daniel Blachowicz','daniel.blachowicz@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Eryk Blachowicz','eryk.blachowicz@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Albert Blachowicz','albert.blachowicz@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Pawel Blachowicz','pawel.blachowicz@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Iza Blachowicz','iza.blachowicz@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Monika Blachowicz','monika.blachowicz@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Anna Blachowicz','anna.blachowicz@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),

('Barbara Glik','barbara.glik@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Adam Glik','adam.glik@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Cecylia Glik','cecylia.glik@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Daniel Glik','daniel.glik@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Eryk Glik','eryk.glik@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Albert Glik','albert.glik@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Pawel Glik','pawel.glik@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Iza Glik','iza.glik@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Monika Glik','monika.glik@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Anna Glik','anna.glik@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),

('Barbara Kowalczyk','barbara.kowalczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Adam Kowalczyk','adam.kowalczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Cecylia Kowalczyk','cecylia.kowalczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Daniel Kowalczyk','daniel.kowalczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Eryk Kowalczyk','eryk.kowalczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Albert Kowalczyk','albert.kowalczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Pawel Kowalczyk','pawel.kowalczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Iza Kowalczyk','iza.kowalczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Monika Kowalczyk','monika.kowalczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Anna Kowalczyk','anna.kowalczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),

('Barbara Mazur','barbara.mazur@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Adam Mazur','adam.mazur@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Cecylia Mazur','cecylia.mazur@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Daniel Mazur','daniel.mazur@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Eryk Mazur','eryk.mazur@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Albert Mazur','albert.mazur@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Pawel Mazur','pawel.mazur@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Iza Mazur','iza.mazur@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Monika Mazur','monika.mazur@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Anna Mazur','anna.mazur@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),

('Barbara Krawczyk','barbara.krawczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Adam Krawczyk','adam.krawczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Cecylia Krawczyk','cecylia.krawczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Daniel Krawczyk','daniel.krawczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Eryk Krawczyk','eryk.krawczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Albert Krawczyk','albert.krawczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Pawel Krawczyk','pawel.krawczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Iza Krawczyk','iza.krawczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Monika Krawczyk','monika.krawczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Anna Krawczyk','anna.krawczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),

('Barbara Polak','barbara.polak@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Adam Polak','adam.polak@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Cecylia Polak','cecylia.polak@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Daniel Polak','daniel.polak@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Eryk Polak','eryk.polak@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Albert Polak','albert.polak@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Pawel Polak','pawel.polak@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Iza Polak','iza.polak@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Monika Polak','monika.polak@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Anna Polak','anna.polak@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),

('Barbara Szewczyk','barbara.szewczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Adam Szewczyk','adam.szewczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Cecylia Szewczyk','cecylia.szewczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Daniel Szewczyk','daniel.szewczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Eryk Szewczyk','eryk.szewczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Albert Szewczyk','albert.szewczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Pawel Szewczyk','pawel.szewczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Iza Szewczyk','iza.szewczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Monika Szewczyk','monika.szewczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER'),
('Anna Szewczyk','anna.szewczyk@gmail.com',"$2a$10$/V2L7BSJ3VMhMJClGm1oWu0YN9.myGsp0HqHsXQ.CMhYMAiFImb2O",'USER');
